---
all:
  hosts:
    server:
      ansible_host: 127.0.0.1
      ansible_port: 2202
      ansible_private_key_file: /home/kita/OTUS/Otus_Unit_22_VPN/.vagrant/machines/server/virtualbox/private_key

    client:
      ansible_host: 127.0.0.1
      ansible_port: 2203
      ansible_private_key_file: /home/kita/OTUS/Otus_Unit_22_VPN/.vagrant/machines/client/virtualbox/private_key